---
- name: 📊 Install Prometheus & Grafana
  hosts: server
  become: yes
  tasks:
    - name: Create monitoring namespace
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: monitoring

    - name: Add Helm repo
      helm_repository:
        name: prometheus-community
        url: https://prometheus-community.github.io/helm-charts

    - name: Install kube-prometheus-stack
      helm:
        name: prometheus
        repo_url: https://prometheus-community.github.io/helm-charts
        chart_ref: prometheus-community/kube-prometheus-stack
        namespace: monitoring
        values:
          grafana:
            adminPassword: prom-operator
            service:
              type: NodePort
              nodePort: 30000